### ISSUE TITLE
Topup with mainnet address fails, CLI gets stuck after this

### ISSUE THREAD

**Issue by nielstron** [bloxbean/yaci-devkit#25]
Trying to top up a mainnet address in the cli fails. This is expected. After that however, the cli does not return to an input field. Trying to Ctrl+C out, I get an obscure error and needed to hit Ctrl+C ~20 times to get back to the CLI

Full log:

```
sudo ./yaci-cli.sh
docker-compose not found, let's try 'docker compose'
WARN[0000] /home/niels/git/yaci-devkit/docker-compose.yml: `version` is obsolete 
12:51:25,525 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.14
12:51:25,529 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - Here is a list of configurators discovered as a service, by rank: 
12:51:25,529 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a -   org.springframework.boot.logging.logback.RootLogLevelConfigurator
12:51:25,529 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - They will be invoked in order until ExecutionStatus.DO_NOT_INVOKE_NEXT_IF_ANY is returned.
12:51:25,529 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - Constructed configurator of type class org.springframework.boot.logging.logback.RootLogLevelConfigurator
12:51:25,533 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - org.springframework.boot.logging.logback.RootLogLevelConfigurator.configure() call lasted 0 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
12:51:25,533 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - Trying to configure with ch.qos.logback.classic.joran.SerializedModelConfigurator
12:51:25,534 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - Constructed configurator of type class ch.qos.logback.classic.joran.SerializedModelConfigurator
12:51:25,535 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.scmo]
12:51:25,536 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.scmo]
12:51:25,536 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - ch.qos.logback.classic.joran.SerializedModelConfigurator.configure() call lasted 2 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
12:51:25,536 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
12:51:25,536 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
12:51:25,537 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
12:51:25,538 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
12:51:25,538 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 2 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
12:51:25,538 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - Trying to configure with ch.qos.logback.classic.BasicConfigurator
12:51:25,540 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - Constructed configurator of type class ch.qos.logback.classic.BasicConfigurator
12:51:25,540 |-INFO in ch.qos.logback.classic.BasicConfigurator@349c1daf - Setting up default configuration.
12:51:25,555 |-INFO in ch.qos.logback.classic.util.ContextInitializer@37ddb69a - ch.qos.logback.classic.BasicConfigurator.configure() call lasted 15 milliseconds. ExecutionStatus=NEUTRAL
12:51:25,934 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@dfddc9a - URL [jar:nested:/app/yaci-cli.jar/!BOOT-INF/classes/!/logback-spring.xml] is not of type file
12:51:25,975 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@4b9df8a - Adding [jar:nested:/app/yaci-cli.jar/!BOOT-INF/lib/spring-boot-3.2.1.jar!/org/springframework/boot/logging/logback/defaults.xml] to configuration watch list.
12:51:25,975 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@dfddc9a - URL [jar:nested:/app/yaci-cli.jar/!BOOT-INF/lib/spring-boot-3.2.1.jar!/org/springframework/boot/logging/logback/defaults.xml] is not of type file
12:51:25,977 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word clr with class [org.springframework.boot.logging.logback.ColorConverter]
12:51:25,977 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word correlationId with class [org.springframework.boot.logging.logback.CorrelationIdConverter]
12:51:25,977 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wex with class [org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter]
12:51:25,977 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wEx with class [org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter]
12:51:25,979 |-WARN in ch.qos.logback.core.joran.action.ParamAction - <param> element is deprecated in favor of a more direct syntax.At line 11
12:51:25,979 |-WARN in ch.qos.logback.core.joran.action.ParamAction - For details see http://logback.qos.ch/codes.html#param
12:51:25,980 |-WARN in ch.qos.logback.core.joran.action.ParamAction - <param> element is deprecated in favor of a more direct syntax.At line 12
12:51:25,980 |-WARN in ch.qos.logback.core.joran.action.ParamAction - For details see http://logback.qos.ch/codes.html#param
12:51:25,980 |-WARN in ch.qos.logback.core.joran.action.ParamAction - <param> element is deprecated in favor of a more direct syntax.At line 13
12:51:25,980 |-WARN in ch.qos.logback.core.joran.action.ParamAction - For details see http://logback.qos.ch/codes.html#param
12:51:26,004 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.catalina.startup.DigesterFactory] to ERROR
12:51:26,004 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5e8ac0e1 - Propagating ERROR level on Logger[org.apache.catalina.startup.DigesterFactory] onto the JUL framework
12:51:26,004 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.catalina.util.LifecycleBase] to ERROR
12:51:26,004 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5e8ac0e1 - Propagating ERROR level on Logger[org.apache.catalina.util.LifecycleBase] onto the JUL framework
12:51:26,004 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.coyote.http11.Http11NioProtocol] to WARN
12:51:26,004 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5e8ac0e1 - Propagating WARN level on Logger[org.apache.coyote.http11.Http11NioProtocol] onto the JUL framework
12:51:26,004 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.sshd.common.util.SecurityUtils] to WARN
12:51:26,004 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5e8ac0e1 - Propagating WARN level on Logger[org.apache.sshd.common.util.SecurityUtils] onto the JUL framework
12:51:26,004 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.tomcat.util.net.NioSelectorPool] to WARN
12:51:26,004 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5e8ac0e1 - Propagating WARN level on Logger[org.apache.tomcat.util.net.NioSelectorPool] onto the JUL framework
12:51:26,004 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.eclipse.jetty.util.component.AbstractLifeCycle] to ERROR
12:51:26,004 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5e8ac0e1 - Propagating ERROR level on Logger[org.eclipse.jetty.util.component.AbstractLifeCycle] onto the JUL framework
12:51:26,004 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.hibernate.validator.internal.util.Version] to WARN
12:51:26,004 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5e8ac0e1 - Propagating WARN level on Logger[org.hibernate.validator.internal.util.Version] onto the JUL framework
12:51:26,004 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.springframework.boot.actuate.endpoint.jmx] to WARN
12:51:26,004 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5e8ac0e1 - Propagating WARN level on Logger[org.springframework.boot.actuate.endpoint.jmx] onto the JUL framework
12:51:26,004 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [FILE]
12:51:26,005 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
12:51:26,009 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
12:51:26,028 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@aafcffa - No compression will be used
12:51:26,029 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/yaci-cli.log
12:51:26,030 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [logs/yaci-cli.log]
12:51:26,030 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [CONSOLE]
12:51:26,030 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
12:51:26,030 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
12:51:26,031 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
12:51:26,031 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5e8ac0e1 - Propagating INFO level on Logger[ROOT] onto the JUL framework
12:51:26,031 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE] to Logger[ROOT]
12:51:26,031 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [FILE] to Logger[ROOT]
12:51:26,031 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@6955cb39 - End of configuration.
12:51:26,032 |-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@235a0c16 - Registering current configuration as safe fallback point

,--.   ,--.            ,--.         ,-----.,--.   ,--.
 \  `.'  /,--,--. ,---.`--'        '  .--./|  |   |  |
  '.    /' ,-.  || .--',--.        |  |    |  |   |  |
    |  | \ '-'  |\ `--.|  |        '  '--'\|  '--.|  |
    `--'  `--`--' `---'`--'         `-----'`-----'`--'
            A BloxBean Project - v0.0.20-beta1 


2024-04-17 12:51:27,150 7 [           main] INFO  o.apache.catalina.core.StandardService   - Starting service [Tomcat]
2024-04-17 12:51:27,151 7 [           main] INFO  org.apache.catalina.core.StandardEngine  - Starting Servlet engine: [Apache Tomcat/10.1.17]
2024-04-17 12:51:27,177 7 [           main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/]       - Initializing Spring embedded WebApplicationContext
yaci-cli:>create-node
[Success] Create cluster folder !!!
[Success] Slot length updated in genesis.json
[Success] Updated configuration.yaml
[Success] Update ports
[Success] Create Cluster : default

###### Node Details (Container) ######
[Node port] 3001
[Node Socket Paths] 
/clusters/default/node-spo1/node.sock
[Submit Api Port] 8090
[Protocol Magic] 42
[Block Time] 1.0 sec
[Slot Length] 1.0 sec
[Start Time] 0


#################### URLS (Host) ####################
[Yaci Viewer] http://localhost:5173
[Yaci Store Swagger UI] http://localhost:8080/swagger-ui.html
[Yaci Store Api URL] http://localhost:8080/api/v1/
[Pool Id] pool1wvqhvyrgwch4jq9aa84hc8q4kzvyq2z3xr6mpafkqmx9wce39zy


#################### Node Ports ####################
[n2n port] localhost:3001
[n2c port (socat)] localhost:3333
devnet:default>create-node -o --start
[Success] Delete existing folder
[Success] Create cluster folder !!!
[Success] Slot length updated in genesis.json
[Success] Updated configuration.yaml
[Success] Update ports
[Success] Create Cluster : default

###### Node Details (Container) ######
[Node port] 3001
[Node Socket Paths] 
/clusters/default/node-spo1/node.sock
[Submit Api Port] 8090
[Protocol Magic] 42
[Block Time] 1.0 sec
[Slot Length] 1.0 sec
[Start Time] 0


#################### URLS (Host) ####################
[Yaci Viewer] http://localhost:5173
[Yaci Store Swagger UI] http://localhost:8080/swagger-ui.html
[Yaci Store Api URL] http://localhost:8080/api/v1/
[Pool Id] pool1wvqhvyrgwch4jq9aa84hc8q4kzvyq2z3xr6mpafkqmx9wce39zy


#################### Node Ports ####################
[n2n port] localhost:3001
[n2c port (socat)] localhost:3333
[Success] Update Start time
[Success] Starting node from directory : /clusters/default/node-spo1
[Success] Started submit api : http://localhost:8090
[Info] Swagger Url to interact with the cluster's node : http://localhost:10000/swagger-ui.html
Waiting for next block...
[Success] Started n2c through socat : localhost:3333
[Success] Yaci store starting ...
Waiting for Yaci Store to start ...
Waiting for Yaci Store to start ...
Waiting for Yaci Store to start ...
Waiting for Yaci Store to start ...
Waiting for Yaci Store to start ...
Waiting for Yaci Store to start ...
Waiting for Yaci Store to start ...
Waiting for Yaci Store to start ...
Waiting for Yaci Store to start ...
Waiting for Yaci Store to start ...
Waiting for Yaci Store to start ...
[OK] Yaci Store Started
Waiting for Yaci Store to start ...
devnet:default>start
A cluster is already running. You can only run one cluster at a time.

devnet:default>topup addr1vxp52cku5u8hrqvttu67t3d33ayl0lwsflhfwqkzkw6230s5f0fsw 1000000
[Txn Cbor] 84a40081825820347e9d3c72ddc52bdb43cf1c44d31507983c102e870398b9205fb8ed125f7e6400018282581d61834562dca70f71818b5f35e5c5b18f49f7fdd04fee9702c2b3b4a8be1b000000e8d4a5100082581d60a0f1aa7dca95017c11e7e373aebcf0c4568cf47ec12b94f8eb5bba8b1b000aa79319abdf07021a000290f907582024ff08a7f728937e5d01cc55619870ba457d17c94659637acabc5584f9dc440da100818258209b0ee7e26318d3675742c8b841b981ae57c37bcbb2cc5625f80606b3256d08145840ba983de6733f552ac492f8aa9c6799b4c95220e0db0f26651d92802b34fb456ab119f63f177df62cfe02247aedb19a3a132333eb2a3535793e74d37d46a5a503f5a11902a2a1636d7367816a546f7075702046756e64
[ERROR] Transaction submission failed. 82028182059f82008202820183080081581d61834562dca70f71818b5f35e5c5b18f49f7fdd04fee9702c2b3b4a8beff
^C2024-04-17 12:53:24,232 7 [ntLoopGroup-4-1] ERROR c.b.cardano.yaci.core.network.Session    - Connection failed
java.lang.IllegalStateException: executor not accepting a task
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:61)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:47)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:189)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:175)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by satran004** [comment]
@nielstron  This is a known issue. I will check if we can terminate the running threads with ctrl+c.

By the way, the above topup error is happening due to the use of a mainnet address. You need to use a testnet address with Yaci Devkit.

Alternatively, you can add topup addresses in the env file to auto-topup during node startup. However, you need to restart the container using './start.sh' after the change.
